In [10]:
import time

In [11]:
import cv2

In [12]:
video = cv2.VideoCapture(0)

In [13]:
check,frame = video.read()

In [14]:
 time.sleep(3)

In [15]:
cv2.imshow("Capturing",frame)

In [16]:
cv2.waitKey(0)

27

In [17]:
video.release()

In [9]:
cv2.destroyAllWindows

<function destroyAllWindows>

In [2]:
import cv2, time
video = cv2.VideoCapture(0)
check,frame = video.read()
time.sleep(3)
cv2.imshow("Capturing", frame)
cv2.waitKey(0)
video.release()
cv2.destroyAllWindows()


In [12]:
import cv2, time
a= 1
video = cv2.VideoCapture(0)
while True:
    a=a+1
    check,frame = video.read()
    print(frame)
    c = cv2.cvtColor(frame, cv2.COLOR_BGRA2RGB)
    cv2.imshow("Capturing", c)
    key = cv2.waitKey(1)
    if key==ord('q'):
        break
        
print(a)
video.release()
cv2.destroyAllWindows()

[[[191 176 181]
  [193 177 182]
  [193 177 182]
  ...
  [ 29  32  31]
  [ 33  30  33]
  [ 32  29  32]]

 [[189 176 182]
  [191 177 184]
  [191 180 184]
  ...
  [ 29  33  33]
  [ 32  34  34]
  [ 29  32  31]]

 [[193 177 182]
  [194 178 183]
  [196 181 186]
  ...
  [ 35  30  33]
  [ 35  31  34]
  [ 35  31  34]]

 ...

 [[192 195 194]
  [184 187 186]
  [181 182 184]
  ...
  [120 122 115]
  [122 125 117]
  [118 120 113]]

 [[170 169 180]
  [163 162 173]
  [158 158 171]
  ...
  [114 119 116]
  [116 120 114]
  [119 123 118]]

 [[151 135 156]
  [154 137 158]
  [152 139 157]
  ...
  [114 121 113]
  [114 121 108]
  [120 127 114]]]
[[[188 177 177]
  [191 179 179]
  [198 180 186]
  ...
  [ 36  33  35]
  [ 37  34  28]
  [ 34  32  25]]

 [[186 178 175]
  [189 180 177]
  [194 183 182]
  ...
  [ 37  33  38]
  [ 40  32  35]
  [ 37  29  33]]

 [[189 178 178]
  [191 179 179]
  [196 182 182]
  ...
  [ 42  34  38]
  [ 41  33  37]
  [ 40  32  35]]

 ...

 [[185 202 199]
  [180 197 194]
  [187 195 192]
  ..

[[[193 177 182]
  [196 181 186]
  [198 180 186]
  ...
  [ 34  26  30]
  [ 35  29  35]
  [ 35  29  35]]

 [[190 179 183]
  [192 182 186]
  [194 181 186]
  ...
  [ 38  32  35]
  [ 30  26  31]
  [ 35  31  36]]

 [[188 180 183]
  [190 182 186]
  [193 183 187]
  ...
  [ 35  30  33]
  [ 34  29  32]
  [ 37  31  34]]

 ...

 [[200 195 203]
  [196 192 199]
  [192 193 198]
  ...
  [121 129 118]
  [121 126 119]
  [120 125 117]]

 [[172 162 184]
  [170 160 182]
  [167 158 180]
  ...
  [117 127 119]
  [119 126 120]
  [117 123 118]]

 [[155 139 159]
  [159 143 164]
  [157 141 162]
  ...
  [117 124 116]
  [118 121 118]
  [114 118 115]]]
[[[190 178 185]
  [191 180 186]
  [194 180 189]
  ...
  [ 31  37  33]
  [ 31  37  33]
  [ 30  35  32]]

 [[190 179 183]
  [191 180 184]
  [194 181 186]
  ...
  [ 33  35  37]
  [ 33  35  37]
  [ 32  33  35]]

 [[191 178 182]
  [192 179 183]
  [196 181 186]
  ...
  [ 37  32  40]
  [ 37  32  40]
  [ 33  29  36]]

 ...

 [[197 186 190]
  [190 179 183]
  [191 176 185]
  ..

[[[198 179 189]
  [198 179 189]
  [199 180 190]
  ...
  [ 37  33  38]
  [ 39  32  40]
  [ 35  28  36]]

 [[194 180 189]
  [194 180 189]
  [197 180 190]
  ...
  [ 36  32  37]
  [ 38  31  37]
  [ 35  29  35]]

 [[189 179 188]
  [190 180 189]
  [192 180 189]
  ...
  [ 36  32  37]
  [ 35  31  36]
  [ 36  32  37]]

 ...

 [[183 173 182]
  [181 171 179]
  [171 160 173]
  ...
  [112 127 117]
  [114 124 115]
  [112 121 113]]

 [[146 137 159]
  [145 135 158]
  [149 137 166]
  ...
  [117 123 118]
  [117 121 116]
  [114 118 113]]

 [[141 125 144]
  [141 125 144]
  [139 123 149]
  ...
  [120 121 118]
  [119 120 117]
  [116 117 115]]]
[[[187 177 181]
  [187 177 181]
  [189 178 182]
  ...
  [ 27  34  33]
  [ 25  33  31]
  [ 27  34  33]]

 [[186 178 182]
  [186 178 182]
  [186 178 184]
  ...
  [ 28  34  35]
  [ 28  34  35]
  [ 28  34  35]]

 [[192 179 183]
  [193 180 184]
  [193 180 184]
  ...
  [ 29  33  33]
  [ 27  34  33]
  [ 27  34  33]]

 ...

 [[174 168 180]
  [171 164 177]
  [169 158 178]
  ..

[[[191 177 184]
  [192 178 185]
  [196 179 189]
  ...
  [ 33  33  31]
  [ 39  31  34]
  [ 39  31  34]]

 [[190 178 186]
  [192 180 189]
  [194 180 189]
  ...
  [ 35  30  33]
  [ 37  29  33]
  [ 37  29  33]]

 [[194 180 189]
  [194 180 189]
  [197 180 190]
  ...
  [ 36  33  35]
  [ 33  33  31]
  [ 33  33  31]]

 ...

 [[176 180 184]
  [168 171 175]
  [168 167 176]
  ...
  [117 127 119]
  [114 125 119]
  [112 123 117]]

 [[153 156 169]
  [150 152 166]
  [148 149 165]
  ...
  [114 126 117]
  [114 125 121]
  [113 123 119]]

 [[133 131 145]
  [140 138 152]
  [139 136 150]
  ...
  [115 127 120]
  [117 125 122]
  [116 124 121]]]
[[[193 175 182]
  [196 177 185]
  [197 178 186]
  ...
  [ 29  32  31]
  [ 31  32  30]
  [ 31  32  30]]

 [[193 176 181]
  [195 177 182]
  [196 178 183]
  ...
  [ 28  35  34]
  [ 32  35  32]
  [ 33  36  33]]

 [[193 177 182]
  [194 178 183]
  [196 181 186]
  ...
  [ 34  35  32]
  [ 35  37  32]
  [ 35  37  32]]

 ...

 [[181 173 183]
  [175 167 178]
  [176 165 178]
  ..

In [ ]:
import numpy as np
import cv2

# multiple cascades: https://github.com/Itseez/opencv/tree/master/data/haarcascades

#https://github.com/Itseez/opencv/blob/master/data/haarcascades/haarcascade_frontalface_default.xml
face_cascade = cv2.CascadeClassifier('C:/Users/Sayali/Desktop/Python/Daily Task/face-mask-detection-keras-master/haarcascade_frontalface_default.xml')
#https://github.com/Itseez/opencv/blob/master/data/haarcascades/haarcascade_eye.xml
eye_cascade = cv2.CascadeClassifier('C:/Users/Sayali/Desktop/Python/Daily Task/face-mask-detection-keras-master/haarcascade_eye.xml')


cap = cv2.VideoCapture(0)

while 1:
    ret, img = cap.read()
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
     
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)

    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
        roi_gray = gray[y:y+h, x:x+w]
        roi_color = img[y:y+h, x:x+w]
        
        eyes = eye_cascade.detectMultiScale(roi_gray)
        for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)

    cv2.imshow('img',img)
    k = cv2.waitKey(30) & 0xff
    if k == 27:
        break

cap.release()
cv2.destroyAllWindows()